# <b>KoBERT
<pre>
python                         pytorch
----------------            ---------------------------
BertTokenizer               AutoTokenizer / AutoModel
    
!pip install torch==2.3.1     
     GPU 사용시 ---> !pip install torch==2.3.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

    
!pip install sentencepiece==0.2.0
!pip install transformers==4.41.2

!pip install onnxruntime==1.18.0   ---> pip install numpy==1.26.4 [torch 미사용시]

| 모델            | 구조      | 특징                         | 장점           | 단점               | 추천 사용         |
| ------------- | ------- | -------------------------- | ------------ | ---------------- | ------------- |
| **KoBERT**    | BERT    | SKT 한국어 특화 BERT            | 안정적, 구현 쉬움   | 성능 최신 모델 대비 낮음   | 입문 / baseline |
| **KoELECTRA** | ELECTRA | Generator-Discriminator 방식 | 빠르고 성능 좋음    | 튜닝 난이도 있음        | 대부분 NLP task  |
| **KcELECTRA** | ELECTRA | SNS/댓글 데이터 특화              | 실사용 데이터에 강함  | 정제 데이터에서는 과적합 가능 | 리뷰, 댓글 분석     |
| **KLUE-BERT** | BERT    | KLUE benchmark 최적화         | 한국어 표준 성능 우수 | 무겁고 느림           | 논문급 성능 필요     |
| **RoBERTa**   | BERT 개선 | 학습 방식 개선 (no NSP 등)        | 높은 성능        | 한국어 특화 아님        | 영어/멀티언어       |

| 구분    | Transformer (Encoder-Decoder) | GPT          | KoBERT       |
| ----- | ----------------------------- | ------------ | ------------ |
| <font color=red><b>대표 구조 | <font color=red><b>Encoder + Decoder             | <font color=red><b>Decoder only | <font color=red><b>Encoder only |
| 방향성   | 양방향 + 생성                      | 단방향 (좌→우)    | 양방향          |
| 학습 방식 | 번역/seq2seq                    | 다음 단어 예측     | 마스킹 복원       |

<img src=  "https://seol8118.github.io/assets/images/book/3minDL/ch08-01-autoencoder-basic-structure.jpg " width =400>

<pre>심화---------------------part2
    
<font color=red><b>서브워드 토크나이저</font></b>
인코더-디코더
어텐션 메커니즘
트랜스포머
   - BERT, KoBERT, *BERT , GPT, *-GPT

전이학습(pre voca훈련 모델)
    : 학습에 사용된 사전(voca) - wiki rows
    : Embedding 100 300 500
    : 허깅페이스 모델 허브 (https://huggingface.co/docs/hub/models-the-hub
                          (https://huggingface.co/models
    : 허깅페이스 API       (https://huggingface.co/docs/inference-providers/tasks/index)

    
<font color=red><b>허깅페이스
    : 자연어(NLP) 특화된 오픈 플랫폼    (유료-API호출 / 무료-다운,로컬구축,CPU)
    : 모델(임베딩), API를 쉽게 공유하는 플랫폼
    : 트랜스포머 주류
    : 다양한 데이터셋
    : 대표적 임베딩(SetenseTransfomer)
    
-----------------------------------------------

In [1]:
!pip install sentencepiece==0.2.0

Collecting sentencepiece==0.2.0
  Downloading sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)
Downloading sentencepiece-0.2.0-cp310-cp310-win_amd64.whl (991 kB)
   ---------------------------------------- 0.0/991.5 kB ? eta -:--:--
   ---------------------------------------- 991.5/991.5 kB 9.2 MB/s  0:00:00
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.2.0

In [3]:
!pip install transformers==4.41.2

Collecting transformers==4.41.2
  Downloading transformers-4.41.2-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: filelock in c:\it\workspace_python\.venv\lib\site-packages (from transformers==4.41.2) (3.25.0)
Collecting huggingface-hub<1.0,>=0.23.0 (from transformers==4.41.2)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in c:\it\workspace_python\.venv\lib\site-packages (from transformers==4.41.2) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\it\workspace_python\.venv\lib\site-packages (from transformers==4.41.2) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\it\workspace_python\.venv\lib\site-packages (from transformers==4.41.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\it\workspace_python\.venv\lib\site-packages (from transformers==4.41.2) (2026.2.28)
Requirement already satisfied: requests in c:\it\workspace_python\.venv\lib\site-packages (from transformers==4.41.2) (2.32.5)
Collecting tokenizers<0.20,>=0.19 (from transformers==4.41.2)
  Downloading tokenizers-0.19.1-cp310-none-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.1 (from transformers==4.41.2)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in c:\it\workspace_python\.venv\lib\site-packages (from transformers==4.41.2) (4.67.2)
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.2)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\it\workspace_python\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.2) (4.15.0)
Requirement already satisfied: colorama in c:\it\workspace_python\.venv\lib\site-packages (from tqdm>=4.27->transformers==4.41.2) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\it\workspace_python\.venv\lib\site-packages (from requests->transformers==4.41.2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\it\workspace_python\.venv\lib\site-packages (from requests->transformers==4.41.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\it\workspace_python\.venv\lib\site-packages (from requests->transformers==4.41.2) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\it\workspace_python\.venv\lib\site-packages (from requests->transformers==4.41.2) (2026.1.4)
Downloading transformers-4.41.2-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ---------- ----------------------------- 2.4/9.1 MB 11.2 MB/s eta 0:00:01
   -------------------- ------------------- 4.7/9.1 MB 11.4 MB/s eta 0:00:01
   ------------------------------- -------- 7.1/9.1 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 11.1 MB/s  0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ---------------------------------------- 0.0/566.4 kB ? eta -:--:--
   ---------------------------------------- 566.4/566.4 kB 9.8 MB/s  0:00:00
Downloading tokenizers-0.19.1-cp310-none-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 10.5 MB/s  0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Installing collected packages: safetensors, fsspec, huggingface-hub, tokenizers, transformers

   -------- ------------------------------- 1/5 [fsspec]
   -------- ------------------------------- 1/5 [fsspec]
   ---------------- ----------------------- 2/5 [huggingface-hub]
   ---------------- ----------------------- 2/5 [huggingface-hub]
   ---------------- ----------------------- 2/5 [huggingface-hub]
   ---------------- ----------------------- 2/5 [huggingface-hub]
   ---------------- ----------------------- 2/5 [huggingface-hub]
   ------------------------ --------------- 3/5 [tokenizers]
   ------------------------ --------------- 3/5 [tokenizers]
   ------------------------ --------------- 3/5 [tokenizers]
   ------------------------ --------------- 3/5 [tokenizers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   ---------------------------------------- 5/5 [transformers]

Successfully installed fsspec-2026.2.0 huggingface-hub-0.36.2 safetensors-0.7.0 tokenizers-0.19.1 transformers-4.41.2

In [2]:
##### !pip install torch==2.3.1 --------- CPU만 사용할 경우
############################# 아래 GPU사용 설치 권장

# <b>GPU확인 : powershell

<pre>
PS C:\WINDOWS\system32> nvidia-smi
Tue Mar 24 14:59:46 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 3GB  WDDM  |   00000000:09:00.0  On |                  N/A |
| 37%   35C    P0             26W /  120W |    2147MiB /   3072MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      3792    C+G   ...on\146.0.3856.62\msedgewebview2.exe      N/A      |
|    0   N/A  N/A      3956    C+G   ...s\System32\ApplicationFrameHost.exe      N/A      |
|    0   N/A  N/A      7456    C+G   C:\Windows\explorer.exe                     N/A      |
                           ----   중략 ---
|    0   N/A  N/A     30424    C+G   ...__8wekyb3d8bbwe\WindowsTerminal.exe      N/A      |
+-----------------------------------------------------------------------------------------+

<pre>
PS C:\WINDOWS\system32> Get-WmiObject Win32_VideoController | Select-Object Name
Name
----
NVIDIA GeForce GTX 1060 3GB

<b>GTX 1060 -- CUDA 11.8까지 안정 -- torch 2.3.1 + cu118

* <font color=red><b>torch + GPU 설치

In [32]:
import sys

!{sys.executable} -m pip install --no-cache-dir torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.3.1
  Downloading https://download.pytorch.org/whl/cu118/torch-2.3.1%2Bcu118-cp310-cp310-win_amd64.whl (2673.0 MB)
     ---------------------------------------- 0.0/2.7 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.7 GB 12.2 MB/s eta 0:03:40
     ---------------------------------------- 0.0/2.7 GB 11.9 MB/s eta 0:03:45
     ---------------------------------------- 0.0/2.7 GB 11.8 MB/s eta 0:03:47
     ---------------------------------------- 0.0/2.7 GB 11.7 MB/s eta 0:03:48
     ---------------------------------------- 0.0/2.7 GB 11.5 MB/s eta 0:03:51
     ---------------------------------------- 0.0/2.7 GB 11.3 MB/s eta 0:03:55
     ---------------------------------------- 0.0/2.7 GB 11.4 MB/s eta 0:03:54
     ---------------------------------------- 0.0/2.7 GB 11.1 MB/s eta 0:04:00
     ---------------------------------------- 0.0/2.7 GB 11.0 MB/s eta 0:04:01
     ---------------------------------------- 0.0/2.7 GB 11.1 MB/s eta 0:03:59
     ---------------------------------------- 0.0/2.7 GB 11.1 MB/s eta 0:03:58
     ---------------------------------------- 0.0/2.7 GB 11.1 MB/s eta 0:03:58
     ---------------------------------------- 0.0/2.7 GB 11.2 MB/s eta 0:03:57
     ---------------------------------------- 0.0/2.7 GB 11.2 MB/s eta 0:03:56
      --------------------------------------- 0.0/2.7 GB 11.3 MB/s eta 0:03:55
      --------------------------------------- 0.0/2.7 GB 11.3 MB/s eta 0:03:55
      --------------------------------------- 0.0/2.7 GB 11.3 MB/s eta 0:03:54
      --------------------------------------- 0.0/2.7 GB 11.4 MB/s eta 0:03:52
      --------------------------------------- 0.0/2.7 GB 11.3 MB/s eta 0:03:53
      --------------------------------------- 0.0/2.7 GB 11.4 MB/s eta 0:03:52
      --------------------------------------- 0.0/2.7 GB 11.4 MB/s eta 0:03:51
      --------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:51
      --------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:50
      --------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:50
      --------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:50
      --------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:50
      --------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:49
      --------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:49
     - -------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:49
     - -------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:48
     - -------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:48
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:47
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:47
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:46
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:46
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:46
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:46
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:45
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:45
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:45
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:44
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:44
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:44
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:43
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:43
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:43
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:44
     - -------------------------------------- 0.1/2.7 GB 11.5 MB/s eta 0:03:43
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:48
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:47
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:47
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:46
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:46
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:46
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:45
     - -------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:45
     -- ------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:45
     -- ------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:44
     -- ------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:44
     -- ------------------------------------- 0.1/2.7 GB 11.3 MB/s eta 0:03:44
     -- ------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:43
     -- ------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:43
     -- ------------------------------------- 0.1/2.7 GB 11.4 MB/s eta 0:03:42
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:42
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:42
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:42
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:41
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:41
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:41
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:40
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:40
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:40
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:40
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:40
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:39
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:39
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:38
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:38
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:38
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:38
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:37
     -- ------------------------------------- 0.2/2.7 GB 11.4 MB/s eta 0:03:37
     -- ------------------------------------- 0.2/2.7 GB 11.5 MB/s eta 0:03:37
     -- ------------------------------------- 0.2/2.7 GB 11.5 MB/s eta 0:03:36
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:36
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:36
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:36
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:35
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:35
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:35
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:35
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:33
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:33
     --- ------------------------------------ 0.2/2.7 GB 11.5 MB/s eta 0:03:33
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:34
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:33
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:33
     --- ------------------------------------ 0.2/2.7 GB 11.4 MB/s eta 0:03:33
     --- ------------------------------------ 0.3/2.7 GB 11.4 MB/s eta 0:03:33
     --- ------------------------------------ 0.3/2.7 GB 11.4 MB/s eta 0:03:32
     --- ------------------------------------ 0.3/2.7 GB 11.4 MB/s eta 0:03:32
     --- ------------------------------------ 0.3/2.7 GB 11.4 MB/s eta 0:03:32
     --- ------------------------------------ 0.3/2.7 GB 11.4 MB/s eta 0:03:32
     --- ------------------------------------ 0.3/2.7 GB 11.4 MB/s eta 0:03:32
     --- ------------------------------------ 0.3/2.7 GB 11.4 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:30
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:30
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:32
     ---- ----------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:31
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:30
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:30
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:30
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:30
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:30
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:29
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:29
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:29
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:29
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:29
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:28
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:28
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:28
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:28
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:27
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:27
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:27
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:27
     ---- ----------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:27
     ----- ---------------------------------- 0.3/2.7 GB 11.4 MB/s eta 0:03:26
     ----- ---------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:26
     ----- ---------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:26
     ----- ---------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:26
     ----- ---------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:26
     ----- ---------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:26
     ----- ---------------------------------- 0.3/2.7 GB 11.3 MB/s eta 0:03:25
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:26
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:25
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:25
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:25
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:25
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:25
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:24
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:24
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:24
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:24
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:23
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:23
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:21
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:21
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:21
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:21
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:21
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:20
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:20
     ----- ---------------------------------- 0.4/2.7 GB 11.4 MB/s eta 0:03:20
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:21
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:22
     ----- ---------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:21
     ------ --------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:21
     ------ --------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:21
     ------ --------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:21
     ------ --------------------------------- 0.4/2.7 GB 11.3 MB/s eta 0:03:22
     ------ --------------------------------- 0.4/2.7 GB 11.2 MB/s eta 0:03:22
     ------ --------------------------------- 0.4/2.7 GB 11.2 MB/s eta 0:03:22
     ------ --------------------------------- 0.4/2.7 GB 11.2 MB/s eta 0:03:23
     ------ --------------------------------- 0.4/2.7 GB 11.1 MB/s eta 0:03:23
     ------ --------------------------------- 0.4/2.7 GB 11.1 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 11.1 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 11.1 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 11.1 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 11.0 MB/s eta 0:03:25
     ------ --------------------------------- 0.4/2.7 GB 11.0 MB/s eta 0:03:25
     ------ --------------------------------- 0.4/2.7 GB 11.0 MB/s eta 0:03:25
     ------ --------------------------------- 0.4/2.7 GB 11.0 MB/s eta 0:03:25
     ------ --------------------------------- 0.4/2.7 GB 11.0 MB/s eta 0:03:25
     ------ --------------------------------- 0.4/2.7 GB 11.0 MB/s eta 0:03:25
     ------ --------------------------------- 0.4/2.7 GB 10.9 MB/s eta 0:03:25
     ------ --------------------------------- 0.4/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.4/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.9 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:24
     ------ --------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:24
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:24
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:24
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:24
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.9 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.9 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:23
     ------- -------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:22
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     ------- -------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:20
     -------- ------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     -------- ------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:21
     -------- ------------------------------- 0.5/2.7 GB 10.7 MB/s eta 0:03:20
     -------- ------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:18
     -------- ------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:18
     -------- ------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:18
     -------- ------------------------------- 0.5/2.7 GB 10.8 MB/s eta 0:03:18
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:18
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:18
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:18
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:18
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:17
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:17
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:17
     -------- ------------------------------- 0.6/2.7 GB 10.7 MB/s eta 0:03:17

In [28]:
# GPU 사용 시
##### !pip install torch==2.3.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

<pre>
Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch==2.3.1 in c:\it\workspace_python\.venv\lib\site-packages (2.3.1+cu121)
Requirement already satisfied: torchvision in c:\it\workspace_python\.venv\lib\site-packages (0.18.1+cu121)
Requirement already satisfied: torchaudio in c:\it\workspace_python\.venv\lib\site-packages (2.3.1+cu121)
Requirement already satisfied: filelock in c:\it\workspace_python\.venv\lib\site-packages (from torch==2.3.1) (3.25.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\it\workspace_python\.venv\lib\site-packages (from torch==2.3.1) (4.15.0)
Requirement already satisfied: sympy in c:\it\workspace_python\.venv\lib\site-packages (from torch==2.3.1) (1.14.0)
Requirement already satisfied: networkx in c:\it\workspace_python\.venv\lib\site-packages (from torch==2.3.1) (3.4.2)
Requirement already satisfied: jinja2 in c:\it\workspace_python\.venv\lib\site-packages (from torch==2.3.1) (3.1.6)
Requirement already satisfied: fsspec in c:\it\workspace_python\.venv\lib\site-packages (from torch==2.3.1) (2026.2.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in c:\it\workspace_python\.venv\lib\site-packages (from torch==2.3.1) (2021.4.0)
Requirement already satisfied: intel-openmp==2021.* in c:\it\workspace_python\.venv\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1) (2021.4.0)
Requirement already satisfied: tbb==2021.* in c:\it\workspace_python\.venv\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1) (2021.13.1)
Requirement already satisfied: numpy in c:\it\workspace_python\.venv\lib\site-packages (from torchvision) (2.2.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\it\workspace_python\.venv\lib\site-packages (from torchvision) (12.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\it\workspace_python\.venv\lib\site-packages (from jinja2->torch==2.3.1) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\it\workspace_python\.venv\lib\site-packages (from sympy->torch==2.3.1) (1.3.0)

* <font color=red><b>설치 후 커널 리부팅 후 아래 확인

In [1]:
# torch - GPU 확인
import torch
import sys

print(torch.__version__)
print(torch.cuda.is_available())
print(sys.executable)
print(torch.__file__)


if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

2.3.1+cu118
True
C:\IT\workspace_python\.venv\Scripts\python.exe
C:\IT\workspace_python\.venv\lib\site-packages\torch\__init__.py
NVIDIA GeForce GTX 1060 3GB

* <font color=red size=4><B>에러 발생 시 지우고 재설치

In [30]:
import sys
!{sys.executable} -m pip uninstall -y torch torchvision torchaudio
!{sys.executable} -m pip uninstall -y torch torchvision torchaudio

Found existing installation: torch 2.3.1+cu118
Uninstalling torch-2.3.1+cu118:
  Successfully uninstalled torch-2.3.1+cu118
Found existing installation: torchvision 0.18.1+cu118
Uninstalling torchvision-0.18.1+cu118:
  Successfully uninstalled torchvision-0.18.1+cu118
Found existing installation: torchaudio 2.3.1+cu118
Uninstalling torchaudio-2.3.1+cu118:
  Successfully uninstalled torchaudio-2.3.1+cu118

WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.
WARNING: Skipping torchaudio as it is not installed.

In [31]:
import os, shutil, site

for p in site.getsitepackages():
    for name in ["torch", "torchvision", "torchaudio"]:
        target = os.path.join(p, name)
        if os.path.exists(target):
            print("remove:", target)
            shutil.rmtree(target, ignore_errors=True)

* <font color=red size=4><B>torch 없이 python만 사용할 경우
* <font color=red size=4><B>numpy 다운그레이드 주의주의주의주의 --> 현재 설치한 모든 모듈 영향 받음

In [5]:
import numpy as np
print(np.__version__)

2.2.6

In [6]:
################## ! pip install numpy==1.26.4 
### !pip install onnxruntime==1.18.0

# 토큰화
* ▁ + 자모 분해

In [8]:
# from transformers import BertTokenizer
# tokenizer = BertTokenizer.from_pretrained("skt/kobert-base-v1")
# print(tokenizer.tokenize("오늘 날씨 좋다"))
import warnings
warnings.filterwarnings("ignore")

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("skt/kobert-base-v1")
tokens = tokenizer.tokenize("오늘 날씨 좋다")
print(tokens)

['▁', 'ᄋ', 'ᅩ늘', '▁', '날ᄊ', 'ᅵ', '▁', '좋다']

In [9]:
print(tokenizer.convert_tokens_to_string(tokens))

오늘 날씨 좋다

# <b>[실습] torch + KoBERT

In [10]:
import pandas as pd
from sqlalchemy import create_engine

In [55]:
engine = create_engine("oracle+cx_oracle://it:0000@localhost:1521/xe")
conn = engine.connect()

In [56]:
df = pd.read_sql("SELECT * FROM craw_ytn_news", conn)
df.head(3)

,seq,title,content,cate,rdate
0,514,왕의 길을 걸어 세계로: BTS '아리랑' 컴백이 남긴 것들 [와이파일],"3월 21일 저녁 8시, 서울 광화문 광장이 멈췄습니다.경복궁 근정문에서 문 하나,...",2,2026.03.23. 14:54
1,515,BTS 광화문 공연이 남긴 질문들...끝나고도 갑론을박,[앵커] \r지난 주말 광화문에서 열린 BTS 공연을 두고 갑론을박이 계속되고 있습...,2,2026.03.23. 12:46
2,516,"뮤지컬 [여명의 눈동자] 결국 조기 폐막...""경영상 이유""",출연료 미지급 논란을 겪은 뮤지컬 '여명의 눈동자'가 결국 조기 폐막했습니다.'여명...,2,2026.03.23. 11:25

# 전처리 & 가공
* 중복제거

In [57]:
df['title'].value_counts()

title
BTS, 60분 동안 광화문 공연..."오늘 밤 못 잊을 거예요"    10
광화문 공연 인파 4만? 10만?...하이브 "감사하고 죄송"       9
라이언 고슬링의 감성 SF 영화...'왕사남' 독주 막을까         9
'왕과 사는 남자' 역대 흥행 3위...누적 매출은 1위          5
임윤찬, 2년 만에 전국투어 리사이틀..."프로그램 직접 기획"      5
                                        ..
기획처 박홍근·해수부 황종우, 오늘 인사청문회                1
오늘 박홍근 기획예산처 장관 후보자 인사 청문회               1
이 대통령, 한국은행 총재 후보자로 신현송 BIS 국장 지명        1
한미훈련기간 '활보'한 김정은...존재감 확인 급했나?           1
국힘, 국정조사 권한쟁의 청구...로텐더홀 규탄대회             1
Name: count, Length: 79, dtype: int64

In [58]:
print(df.shape)
df = df.drop_duplicates(subset=['title']).reset_index(drop=True)
print(df.shape)

(267, 5)
(79, 5)

In [59]:
import os
os.environ["HF_HUB_DISABLE_XET"] = "1"

import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity

tokenizer = AutoTokenizer.from_pretrained("skt/kobert-base-v1")
model = AutoModel.from_pretrained("skt/kobert-base-v1")

texts = df["content"].fillna("").astype(str).tolist()

inputs = tokenizer(
    texts,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=64
)

with torch.no_grad():
    outputs = model(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"]
    )

# emb = outputs.last_hidden_state[:, 0, :].cpu().numpy()
# sim_matrix = cosine_similarity(emb, emb)

emb = outputs.last_hidden_state[:, 0, :]
sim_matrix = torch.nn.functional.cosine_similarity(
    emb.unsqueeze(1), emb.unsqueeze(0), dim=-1
)
print(sim_matrix.shape)
print(sim_matrix)

torch.Size([79, 79])
tensor([[1.0000, 0.9080, 0.8953,  ..., 0.8700, 0.8922, 0.8353],
        [0.9080, 1.0000, 0.9279,  ..., 0.9271, 0.9267, 0.9034],
        [0.8953, 0.9279, 1.0000,  ..., 0.9171, 0.8954, 0.9236],
        ...,
        [0.8700, 0.9271, 0.9171,  ..., 1.0000, 0.8548, 0.9007],
        [0.8922, 0.9267, 0.8954,  ..., 0.8548, 1.0000, 0.9256],
        [0.8353, 0.9034, 0.9236,  ..., 0.9007, 0.9256, 1.0000]])

In [60]:
sim_matrix.shape

torch.Size([79, 79])

In [61]:
tfidf_cos_df = pd.DataFrame(sim_matrix.tolist(), index=df['title'] , columns=df['title'])
tfidf_cos_df.head(3)

title,왕의 길을 걸어 세계로: BTS '아리랑' 컴백이 남긴 것들 [와이파일],BTS 광화문 공연이 남긴 질문들...끝나고도 갑론을박,"뮤지컬 [여명의 눈동자] 결국 조기 폐막...""경영상 이유""",'왕과 사는 남자' 역대 흥행 3위...누적 매출은 1위,"임윤찬, 2년 만에 전국투어 리사이틀...""프로그램 직접 기획""","하이브 사옥 1층에 BTS 팝업 운영...""사전 예약 뒤 이용""",넷플릭스 'BTS 컴백 라이브' 영화 부문 1위...77개 국가에서 정상,"BTS 컴백 라이브, 넷플릭스 글로벌 1위…77개국서 정상",라이언 고슬링의 감성 SF 영화...'왕사남' 독주 막을까,"광화문 공연 인파 4만? 10만?...하이브 ""감사하고 죄송""",...,"추미애 ""법사위원장 사임...경기도 승리 이끌 것""","[속보] 추미애 ""검찰개혁 완수...법사위원장 내려놓는다""",김정은 국무위원장 재추대...최고인민회의 수장 조용원,"주호영·이진숙 ""컷오프 수용 불가""...강력대응 예고","민주 ""대전 화재, 원인 규명·온전한 보상에 최선""","기획처 박홍근·해수부 황종우, 오늘 인사청문회",오늘 박홍근 기획예산처 장관 후보자 인사 청문회,"이 대통령, 한국은행 총재 후보자로 신현송 BIS 국장 지명",한미훈련기간 '활보'한 김정은...존재감 확인 급했나?,"국힘, 국정조사 권한쟁의 청구...로텐더홀 규탄대회"
title,,,,,,,,,,,,,,,,,,,,,
왕의 길을 걸어 세계로: BTS '아리랑' 컴백이 남긴 것들 [와이파일],1.000000,0.908019,0.895303,0.873459,0.874205,0.878740,0.895826,0.855646,0.862950,0.900422,...,0.874942,0.917033,0.898652,0.880638,0.887097,0.886889,0.865878,0.869997,0.892221,0.835275
BTS 광화문 공연이 남긴 질문들...끝나고도 갑론을박,0.908019,1.000000,0.927917,0.916623,0.896962,0.927742,0.922300,0.875726,0.947303,0.939644,...,0.899706,0.929263,0.918956,0.909765,0.912892,0.908867,0.893092,0.927071,0.926717,0.903385
"뮤지컬 [여명의 눈동자] 결국 조기 폐막...""경영상 이유""",0.895303,0.927917,1.000000,0.898437,0.920952,0.901120,0.918184,0.865600,0.905455,0.895929,...,0.920846,0.951173,0.919512,0.925668,0.919181,0.896567,0.901237,0.917113,0.895430,0.923587

In [62]:
search_text = "BTS"
search_list = tfidf_cos_df[tfidf_cos_df.index.str.contains(search_text)].index
print(f"검색 결과 뉴스 : {len(search_list)}건\n")
for title_str in search_list[:5]:
    print(title_str)

검색 결과 뉴스 : 21건

왕의 길을 걸어 세계로: BTS '아리랑' 컴백이 남긴 것들 [와이파일]
BTS 광화문 공연이 남긴 질문들...끝나고도 갑론을박
하이브 사옥 1층에 BTS 팝업 운영..."사전 예약 뒤 이용"
넷플릭스 'BTS 컴백 라이브' 영화 부문 1위...77개 국가에서 정상
BTS 컴백 라이브, 넷플릭스 글로벌 1위…77개국서 정상

In [79]:
search_title = "BTS"
print(df[df['title'].str.contains(search_title, regex=False, na=False)]['title'] [:5] )

#tfidf_cos_df.loc[search_title].sort_values(ascending=False)[0:6] 
tfidf_cos_df.iloc[0].sort_values(ascending=False)[1:6]

0    왕의 길을 걸어 세계로: BTS '아리랑' 컴백이 남긴 것들 [와이파일]
1              BTS 광화문 공연이 남긴 질문들...끝나고도 갑론을박
5         하이브 사옥 1층에 BTS 팝업 운영..."사전 예약 뒤 이용"
6    넷플릭스 'BTS 컴백 라이브' 영화 부문 1위...77개 국가에서 정상
7            BTS 컴백 라이브, 넷플릭스 글로벌 1위…77개국서 정상
Name: title, dtype: object

title
BTS, 60분 동안 광화문 공연..."오늘 밤 못 잊을 거예요"    0.945265
BTS '아리랑' 발매 첫날 판매량 400만 육박             0.937430
저녁 8시 광화문 공연..."서프라이즈 있다"               0.923040
[속보] 추미애 "검찰개혁 완수...법사위원장 내려놓는다"        0.917033
광화문 모이는 전 세계 '아미'들...곳곳 보랏빛 풍경          0.914849
Name: 왕의 길을 걸어 세계로: BTS '아리랑' 컴백이 남긴 것들 [와이파일], dtype: float64

In [85]:
search_title = "대구"
print(df[df['title'].str.contains(search_title, regex=False, na=False)]['title'] [:5] )

#tfidf_cos_df.loc[search_title].sort_values(ascending=False)[0:6] 
tfidf_cos_df.iloc[54].sort_values(ascending=False)[1:6]

54    이정현, '대구 컷오프' 논란에 "특정인 겨냥 아냐...더 크게 쓰려는 전략"
59        "대구 컷오프, 장동혁 요청과 다른 결론...최고위 논의 대상은 아냐"
64                  정청래 "김부겸, 대구 필승카드"...공식 출마 요청
Name: title, dtype: object

title
국민의힘 "조작 기소 국조? 대통령도 죄 지으면 감옥가야"    0.971748
국민의힘, 서울시장 '3인 경선'...오세훈·박수민·윤희숙    0.970695
국힘, 국정조사 권한쟁의 청구...로텐더홀 규탄대회        0.969694
'포항 컷오프' 김병욱 삭발..."공정 경선까지 단식"      0.968034
주호영·이진숙 "컷오프 수용 불가"...강력대응 예고       0.963230
Name: 이정현, '대구 컷오프' 논란에 "특정인 겨냥 아냐...더 크게 쓰려는 전략", dtype: float64

# [샘플] torch 사용안할 경우

In [18]:
# import onnxruntime as ort
# import numpy as np
# from transformers import BertTokenizer
# from sklearn.metrics.pairwise import cosine_similarity

```python

# 1. tokenizer / ONNX 모델 로드
tokenizer = BertTokenizer.from_pretrained("skt/kobert-base-v1")
session = ort.InferenceSession("kobert.onnx")

# 2. 문장 → 임베딩 함수
def get_embeddings(texts):
    inputs = tokenizer(
        texts,
        return_tensors="np",
        padding=True,
        truncation=True,
        max_length=64
    )
    outputs = session.run(
        None,
        {
            "input_ids": inputs["input_ids"],
            "attention_mask": inputs["attention_mask"]
        }
    )
    return outputs[0][:, 0, :]   # CLS 벡터

# 3. df['contents'] → 임베딩
emb = get_embeddings(df['contents'].tolist())

# 4. 코사인 유사도
sim_matrix = cosine_similarity(emb, emb)

print(sim_matrix.shape)
print(sim_matrix)